### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by Niggler** [ArtemGordinsky/SpotiFree#19]
you know the drill

**Comment by blag** [comment]
@The-AJ26: This is licensed under the 2-clause BSD license (license file is here: [https://github.com/ArtemGordinsky/SpotiFree/blob/master/SpotiFree/License.txt](https://github.com/ArtemGordinsky/SpotiFree/blob/master/SpotiFree/License.txt)).

@ArtemGordinsky: It's customary to put a LICENSE file (usually no extension necessary, or .md extension if Markdown, or .txt if you choose) in the *root* of the project, and to have a quick "This project is licensed under the two clause BSD license, see LICENSE for more information." section towards the bottom of the README (see [Dokku](https://github.com/progrium/dokku) for an okay-ish example). I can fork and create a PR for this if you'd like.

This issue can be closed, as far as I can tell.
