### ISSUE TITLE
Spotify gets relaunched on quit

### ISSUE THREAD

**Issue by mfpierre** [ArtemGordinsky/SpotiFree#40]
Hi,

While using Spotifree and after playing one song (you can just go directly to the end of the song) when I quit Spotify (+Q) it gets immediately relaunched and hidden.

It is quite annoying since I have to quit Spotify two times in a row after each use.

Thanks

**Comment by E-n-e-a-s** [comment]
Found it. This will also be fixed in the next version...

**Comment by mfpierre** [comment]
Fix confirmed in 1.6, thanks! :+1:
