### ISSUE TITLE
Ads Not Blocked

### ISSUE THREAD

**Issue by The-AJ26** [ArtemGordinsky/SpotiFree#41]
I have been using spotifree and reccomending it to all my friends at absoloutely love it! Recently I was using Spotifree and it showed "active" and when the ad came on (It was about downtown abbey by warner music) and this ad made spotifree "offline" which is the state in which spotify is paused. This makes me think that spotify may be testing of how to make this app not work. :/

**Comment by shatteringlass** [comment]
I don't know how you fixed this, or if this were a true issue in the first place; anyways last night I was prompted to update to 0.9.16.19.g1c9463fe and I carelessly did. Now Spotifree does not block any ad. I would gladly help with debug if I only knew how. I'm afraid they really changed the way the client behaves when playing ads.

**Comment by ArtemGordinsky** [comment]
Hey @shatteringlass,
I have the same version, and it works fine. I guess there was a glitch in Spotify at some point that breaks its AppleScript APIs on update. Over there at #35, a couple of users have reported that they fixed this issue by completely reinstalling Spotify.
