### ISSUE TITLE
Remains inactive

### ISSUE THREAD

**Issue by danielegenta** [ArtemGordinsky/SpotiFree#43]
Hello guys,
i've installed spotifree to remove ads from spotify free but it doesn't turn active, in fact an icons is showed in the top-bar of my mac but, if i click on it, it says 'inactive'.
Thank you in advance!

**Comment by The-AJ26** [comment]
Common mistake, when an ad comes the icon will turn red and say active it will also be active and colored in black if spotify is playing. running will not activate anything.

**Comment by danielegenta** [comment]
When is playing you are right, the icon turns black...i have not seen the icon red.
Anyway thank you for the answer and sorry for the rookie mistake

**Comment by The-AJ26** [comment]
My bad completely I'm using a quite old version of spotifree on my mac...I just reinstalled on my friends device and it seems now that it has an X over it when it mutes, at first when I launched spotify it didn't mute the ads but after a quick command + alt + escape forcequit and relaunch it worked perfectly. Hope it helps.
