### ISSUE TITLE
won't mute Ads

### ISSUE THREAD

**Issue by anonmoez** [ArtemGordinsky/SpotiFree#44]
For a few weeks my Spotifree won't block the Ads on my mac. I tried to reinstall, but it didn't fix the issue.
It's still active and there are no Update available. Do you have any thoughts?

**Comment by Pesa** [comment]
Same problem here, Spotify version 0.9.16.19.g1c9463fe

**Comment by ArtemGordinsky** [comment]
Hey guys,
Have you tried reinstalling Spotify using [these instructions](https://support.spotify.com/us/learn-more/faq/#!/article/reinstallation-of-spotify)? There seems to be a glitch in Spotify breaking the AppleScript interface, and it usually goes away after a complete reinstall.

**Comment by Pesa** [comment]
Reinstalling put an older version (0.9.15.27.g87efe634) on my system, so I'm unable to say whether the problem is really fixed until Spotify decides to update itself again.

**Comment by The-AJ26** [comment]
Have you tried a command+alt+escape forcequit + relaunch after reinstall of both spotify and spotifree?

**Comment by Pesa** [comment]
What's that supposed to accomplish?

**Comment by ArtemGordinsky** [comment]
@Pesa Have you received any updates yet?

**Comment by Pesa** [comment]
nothing yet

**Comment by anonmoez** [comment]
@ArtemGordinsky The instructions seemd to work for me, thx.

**Comment by iiiGerardoiii** [comment]
yup, that fixed it @ArtemGordinsky, thanks

Everyone do what Artem said!

**Comment by didjeridou** [comment]
Worked for me too! Thanx @ArtemGordinsky

**Comment by fait1ux** [comment]
Unfortunately I am still having this problem. When spottily is open and playing music already then spotifree instantly gets shutdown and disappears from my dock. Keep repeating and same action occurs. Sometimes I can get spotifree to stay in dock by opening first and then spottily, and says its blocking ads but it doesn't. Sorry Mr. Gordinsky for the trouble. I tried your instructions again to no avail, but perhaps I am doing it wrong. All the best sir.

**Comment by ArtemGordinsky** [comment]
@fait1ux Spotifree does not retain its Dock icon once it's launched. Do you see it in the menubar?

**Comment by Pesa** [comment]
I finally received the update, to version 0.9.16.25.g241bf986 this time, and Spotifree broke again.

**Comment by ArtemGordinsky** [comment]
@Pesa Okay, let's try and figure out what's going on:
1. Download [this script](http://cl.ly/2W2p2e3D2G1u), run it and give me the results. Like this:
![screen shot 2015-03-03 at 8 45 23 am](https://cloud.githubusercontent.com/assets/1506254/6457687/0214f01a-c182-11e4-9ac4-20a58e332d45.png)
2. Follow the Spotify [reinstallation instructions](https://support.spotify.com/us/learn-more/faq/#!/article/reinstallation-of-spotify) again, but skip the 6th step. Then relaunch the app and wait for an ad to come on. This will tell us if this version breaks Spotifree indeed.

**Comment by shaharz** [comment]
https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/New-Mac-Update-AppleScript-support-removed/td-p/995843

@ArtemGordinsky FYI, your debug script fails with "Syntax Error: Expected end of line but found identifier." on "state". In addition, "Open Dictionary..."  doesn't seem to work for Spotify.app anymore. :disappointed:

**Comment by ArtemGordinsky** [comment]
@shaharz I hope the Spotify team has simply delayed the AppleScript implementation in the new version. Either that, or the day of Spotifree's demise has finally come.

**Comment by Pesa** [comment]
This is the output of the script when a spot is playing:

```
tell application "Spotify"
	get player state
		--> playing
	get artist of current track
		--> "Spotify"
	get name of current track
		--> "Spotify"
	get duration of current track
		--> 26
	get popularity of current track
		--> 0
	get track number of current track
		--> 0
end tell
Result:
0
```

and when an actual song is playing:

```
tell application "Spotify"
	get player state
		--> playing
	get artist of current track
		--> "Cream"
	get name of current track
		--> "I'm So Glad - Live"
	get duration of current track
		--> 379
	get popularity of current track
		--> 41
	get track number of current track
		--> 1
end tell
Result:
1
```

**Comment by ArtemGordinsky** [comment]
Thanks! This is version 1.0.1, right? And Spotifree doesn't work?

**Comment by Pesa** [comment]
version 0.9.16.25.g241bf986

I also reset Caches and Application Support, and it still doesn't mute ads.

**Comment by ArtemGordinsky** [comment]
Okay. Does Spotifree become "active" when Spotify is playing? Have you tried restarting it?
Also, would you please run the script again when an ad comes on?

**Comment by Pesa** [comment]
> Does Spotifree become "active" when Spotify is playing?

Yes

> Have you tried restarting it?

Yes

> Also, would you please run the script again when an ad comes on and tell me what it returns?

See my previous comment above.

**Comment by E-n-e-a-s** [comment]
Found the bug. I'll fix it soon.

**Comment by E-n-e-a-s** [comment]
Does it work with the newest Spotify and Spotifree now?

**Comment by thibmaek** [comment]
Nope, I just updated to 1.0.1.1060.gc75ebdfd but Spotifree is not blocking ads

**Comment by E-n-e-a-s** [comment]
Did you also update Spotifree to version 1.6?
And restarted everything?

**Comment by Pesa** [comment]
Spotifree v1.6 works for me (with Spotify 1.0.1.1060)

Thanks a lot for the quick fix!

**Comment by Usbloom** [comment]
it does not work for me. (spotify free 1.0.1.1060.gc75ebdfb / spotifree 1.6).
Spotifree does a single time, then I have to close & restart it to work again.

**Comment by The-AJ26** [comment]
@ArtemGordinsky 
Relax man Spotify hasn't done anything because the rest of the people not commenting, for them its working perfectly. These are the only few people who are having issues.

**Comment by E-n-e-a-s** [comment]
I think this is fixed for everyone who uses the latest Spotify & latest Spotifree.
