### ISSUE TITLE
Spotifree broken with latest update 0.9.16.25.g241bf986.

### ISSUE THREAD

**Issue by carthach** [ArtemGordinsky/SpotiFree#46]
Version 0.9.16.25.g241bf986.

Not muting Spotify ads. Maybe they've changed something like the detection of track 0.

Happening for anyone else?

**Comment by mpitt** [comment]
Same issue with Spotify version 1.0.1.1060.gc75ebdfd.

**Comment by gina4eva** [comment]
The same thing is happening to me. It worked perfectly until last night. I re-downloaded it and it's still not working in version 1.5

**Comment by ArtemGordinsky** [comment]
@carthach Have you tried following the [troubleshooting instructions](http://spotifree.gordinskiy.com/troubleshooting.html)?
@mpitt Doubtfully the same. I have 0.9.16.25, and AppleScript support is still there.
@gina4eva What's your Spotify version?

**Comment by gina4eva** [comment]
Spotify version 1.0.1.1060.gc75ebdfd. I re-downloaded spotifree and it's still not working. It worked perfectly before last night. Thank you!

**Comment by ArtemGordinsky** [comment]
@gina4eva Sorry, Spotify of versions newer than 0.9.16 work with Spotifree anymore. I don't know if this is permanent, but for the time being you can download an older version [here](https://www.dropbox.com/s/70puzopg60tfv0e/Spotify-0.9.16.zip?dl=0) (quit Spotify and replace it with the downloaded app).

**Comment by gina4eva** [comment]
@ArtemGordinsky Thank you for the download! It seems to be working! Thank you!! That's weird Spotify updated itself without me doing anything or knowing about it.

**Comment by gina4eva** [comment]
@ArtemGordinsky Oh no. It's not actually working. Spotifree says it's active and I'm using the older version of Spotify you gave me, but the adds are audible. Thank you for your help anyway.

**Comment by innerletme** [comment]
Spotifree 1.5 is working with Spotify 0.9.15.27.g87efe634 although not with the version of 0.9.16 you uploaded, @ArtemGordinsky! To get the 9.15 I went to the Spotify page and downloaded a fresh copy, it appears that they haven't rolled out the 0.9.16+ for new users yet. Get it while it's still up. :)

**Comment by carthach** [comment]
http://spotify.en.uptodown.com/mac/old 0.9.15 version there.

**Comment by ArtemGordinsky** [comment]
@carthach Thanks for the link! I guess 0.9.16 didn't work for you either?

**Comment by carthach** [comment]
Afraid not!

**Comment by jessesquires** [comment]
Confirmed broken on `1.0.1.1060.gc75ebdfd`

@ArtemGordinsky - Am I understanding you correctly that Spotifree is *permanently* broken? What changed to cause this?

Previous 1.x version *were* working for me.

**Comment by samuela** [comment]
Same as @mpitt here.

**Comment by ArtemGordinsky** [comment]
@jessesquires As far as I can tell, since 1.0.1 Spotify [has lost](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/New-Mac-Update-AppleScript-support-removed/td-p/995843) its AppleScript interface. I'm not sure if this was caused by a bug, or it was taken out on purpose to counteract Spotifree.

**Comment by jessesquires** [comment]
@ArtemGordinsky - Ahh interesting.

Also of note with this latest release:
Previously, if you muted your computer from the keyboard (F10) the ad would pause. Thus, forcing you to listen to the ad. Now, this is no longer the case. You can mute your audio and the ad will continue to play.

I wonder if these changes are related?

**Comment by gina4eva** [comment]
@carthach Thank you!! That version is working! Thank you.

**Comment by fehmi** [comment]
@carthach @gina4eva Old version is working but it has auto update feature. It installs the new version after every restart :(

**Comment by ArtemGordinsky** [comment]
@fehmi 
I haven't checked if it works now, but I used to be able to stop auto updates by following this guideline:
1. Quit **Spotify**;
2. Press **⇧ + ⌘ + G**, paste in **~/Library/Application Support/Spotify**;
3. If present, delete **Spotify_new.archive** and **Spotify_new.archive.sig**;
4. Open a text editor (e.g. Sublime Text);
5. Create two blank documents named **Spotify_new.archive** and **Spotify_new.archive.sig**;
6. Save both to **~/Library/Application Support/Spotify**;
7. Right click each file and go to **Get Info**
8. Check the **Locked** checkbox on each and close info the windows;
9. Start Spotify again.

**Comment by carthach** [comment]
https://gist.github.com/AllanLRH/1a5f61362081a488fac1

**Comment by fehmi** [comment]
@ArtemGordinsky @carthach Works that way with 0-9-15-17. Thank you very much.

**Comment by E-n-e-a-s** [comment]
The AppleScript interface is still there!!!
Try moving Spotify ▸ Contents ▸ Resources ▸ applescript ▸ Spotify.sdef
to Spotify ▸ Contents ▸ Resources ▸ Spotify.sdef and restart Spotify & Spotifree.

**Comment by ArtemGordinsky** [comment]
@E-n-e-a-s Great! Glad to see you here :)

**Comment by jessesquires** [comment]
:beers: :clap:

**Comment by samuela** [comment]
Hmm, fix doesn't seem to work for me. That said, it does show up on the AppleScript Editor now.

**Comment by E-n-e-a-s** [comment]
Yep, this is because there is a bug in ad detection anyway. New version will be out probably tomorrow.

**Comment by fehmi** [comment]
Seems to new version will be out soon. How can we re enable auto update then :)

**Comment by gina4eva** [comment]
@carthach Thank you for the disabling-Spotify-autoupdate script! Everything is working great now.

**Comment by carthach** [comment]
It's not my script, but glad to share the find!

**Comment by E-n-e-a-s** [comment]
latest Spotify + latest Spotifree = ♥

**Comment by jessesquires** [comment]
:clap: :beer: thanks @E-n-e-a-s !

**Comment by samuela** [comment]
@E-n-e-a-s hallelujah! you da best!
