### ISSUE TITLE
Doesn't work with new Spotify.

### ISSUE THREAD

**Issue by udu5syjt1syj5s51t6y** [ArtemGordinsky/SpotiFree#48]
It automatically crash just after it opens.

**Comment by E-n-e-a-s** [comment]
Same as #47 I guess?

**Comment by mrjiaruiwang** [comment]
Likely same issue. A few days ago on Mountain Lion, I got a notification that I was "opening Spotify for the first time" and realized that they updated the client. Recently, I upgraded to Yosemite and tried opening it, but same behavior. The icon turns on for ~10 seconds, then crashes.

**Comment by E-n-e-a-s** [comment]
I have seriously no idea what causes this crash, because I can't reproduce it. Do you have some crash logs? The more logs I get the more informations I can work with.

**Comment by udu5syjt1syj5s51t6y** [comment]
From Console.app:
14/03/15 16:32:38,265 Spotifree[2393]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
14/03/15 16:32:38,338 Spotifree[2393]: warning: failed to get scripting definition from /Applications/Spotify.app; it may not be scriptable.
14/03/15 16:32:38,339 Spotifree[2393]: -[SBApplication playerState]: unrecognized selector sent to instance 0x60800005fce0
14/03/15 16:32:38,340 Spotifree[2393]: An uncaught exception was raised
14/03/15 16:32:38,340 Spotifree[2393]: -[SBApplication playerState]: unrecognized selector sent to instance 0x60800005fce0
14/03/15 16:32:38,340 Spotifree[2393]: (
	0   CoreFoundation                      0x00007fff8cfae50c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93e3e76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8cfb157d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8cef7524 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff8cef7098 _CF_forwarding_prep_0 + 120
	5   Spotifree                           0x0000000100002394 Spotifree + 9108
	6   Spotifree                           0x0000000100001ba7 Spotifree + 7079
	7   Spotifree                           0x0000000100001c1e Spotifree + 7198
	8   Spotifree                           0x0000000100003055 Spotifree + 12373
	9   CoreFoundation                      0x00007fff8cebb2df -[NSSet makeObjectsPerformSelector:] + 223
	10  AppKit                              0x00007fff96077fcd -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1216
	11  AppKit                              0x00007fff960572b5 loadNib + 384
	12  AppKit                              0x00007fff960567db +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
	13  AppKit                              0x00007fff96056597 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	14  AppKit                              0x00007fff96056363 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	15  AppKit                              0x00007fff9604ef99 NSApplicationMain + 605
	16  Spotifree                           0x0000000100001824 Spotifree + 6180
	17  ???                                 0x0000000000000001 0x0 + 1
)
14/03/15 16:32:38,341 Spotifree[2393]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBApplication playerState]: unrecognized selector sent to instance 0x60800005fce0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8cfae50c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93e3e76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8cfb157d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8cef7524 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff8cef7098 _CF_forwarding_prep_0 + 120
	5   Spotifree                           0x0000000100002394 Spotifree + 9108
	6   Spotifree                           0x0000000100001ba7 Spotifree + 7079
	7   Spotifree                           0x0000000100001c1e Spotifree + 7198
	8   Spotifree                           0x0000000100003055 Spotifree + 12373
	9   CoreFoundation                      0x00007fff8cebb2df -[NSSet makeObjectsPerformSelector:] + 223
	10  AppKit                              0x00007fff96077fcd -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1216
	11  AppKit                              0x00007fff960572b5 loadNib + 384
	12  AppKit                              0x00007fff960567db +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
	13  AppKit                              0x00007fff96056597 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	14  AppKit                              0x00007fff96056363 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	15  AppKit                              0x00007fff9604ef99 NSApplicationMain + 605
	16  Spotifree                           0x0000000100001824 Spotifree + 6180
	17  ???                                 0x0000000000000001 0x0 + 1
)
14/03/15 16:32:38,354 com.apple.xpc.launchd[1]: (com.apple.ReportCrash[2394]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
14/03/15 16:32:38,986 com.apple.xpc.launchd[1]: (de.eneas.Spotifree.86368[2393]) Service exited due to signal: Abort trap: 6
14/03/15 16:32:39,032 ReportCrash[2394]: Saved crash report for Spotifree[2393] version 1.5 (1.5) to /Users/MyName/Library/Logs/DiagnosticReports/Spotifree_2015-03-14-163239_MyMac.crash
14/03/15 16:32:47,342 com.apple.xpc.launchd[1]: (edu.northwestern.cs.aqualab.namehelp.service[2395]) Service could not initialize: Unable to set current working directory. error=2, path=/Applications/namehelp.app/Contents/Resources/: 14D87p: xpcproxy + 12891 [1227][17620F9B-1A7F-3856-B6D0-70B458D2C8B9]: 0x2
14/03/15 16:32:47,342 com.apple.xpc.launchd[1]: (edu.northwestern.cs.aqualab.namehelp.service) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by ArtemGordinsky** [comment]
@udu5syjt1syj5s51t6y You are using Spotifree 1.5, but we have already released 1.6 last week. You may want to update before posting logs here.

**Comment by udu5syjt1syj5s51t6y** [comment]
I'm sorry, I couldn't verify updates since it crashed every time. 
I'm glad to see that now all works as it should.
Thank you for the support.
