### ISSUE TITLE
Crash on OS X 10.6.8

### ISSUE THREAD

**Issue by ArtemGordinsky** [ArtemGordinsky/SpotiFree#49]
```
dyld: Symbol not found: _kSecDigestSHA1
  Referenced from: /Applications/Spotifree.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Applications/Spotifree.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle
Trace/BPT trap
```

Sparkle 1.9 claims to be compatible with 10.6, and I can't find any similar issues in their repository. Not sure if it's the problem in their library or if we are doing something wrong.

**Comment by E-n-e-a-s** [comment]
As I just read it's not compatible with 10.6 anymore. I don't know, whether we should switch back to Sparkle 1.5b, because of that.

**Comment by ArtemGordinsky** [comment]
Sorry, don't know how I could have misread that :)
>[...] switch back to Sparkle 1.5b

Are we using any specific features from 1.9? By the way, I see only 1.8 on their [website](http://sparkle-project.org/).

**Comment by E-n-e-a-s** [comment]
No. I'll switch to 1.6.1. It is the most recent version which supports Snow Leopard
