### ISSUE TITLE
Why Spotifree stuck at mute state after ad?

### ISSUE THREAD

**Issue by fehmi** [ArtemGordinsky/Spotifree#50]
Not everytime but sometimes. I don't know how you can reproduce this issue but it is really annoying.

**Comment by gedeminas** [comment]
Same here, I stopped using Spotifree, temporarily I hope.

**Comment by E-n-e-a-s** [comment]
I'm really sorry, but I don't have any time to fix anything until Friday. Maybe [the experimental version](https://www.dropbox.com/s/zgd1rz1bmm9qyl9/Spotifree.zip?dl=1) does it for you until I can focus on Spotifree again. Or maybe anyone else knows how to fix this :)

**Comment by ArtemGordinsky** [comment]
Hey guys,
Never heard of this issue before. What are your Spotifree and Spotify versions? Can you recall when this started happening?

**Comment by joshwertheim** [comment]
Hey @ArtemGordinsky.

It's happening to me too. Running Spotify (ver. 1.0.1.1060.gc75ebdfd) and Spotifree (ver. 1.6).

Doesn't seem to happen after every ad, but it probably happens about half the time.

**Comment by gedeminas** [comment]
Hey,
if I recall correctly it started happening only after latest Spotify update (to 1.0.1.1060.gc75ebdfd) and Spotifree update (to 1.6). And I updated both of them in one day, so.

**Comment by flopflip21** [comment]
Same as above

**Comment by gkiely** [comment]
Same issue:

Spotify version: 1.0.1.1060.gc75ebdfd
Spotifree version: 1.6
Yosemite 10.10.2

It also disables all sounds for my macbook and the only way I've found to get it back is by restarting.

**Comment by ArtemGordinsky** [comment]
@gkiely Wait, Spotifree shouldn't mangle with the system sound at all. Are you sure you don't have some other apps like smutefy or soundflower installed? Can you look for something spotifree- or sound-related in the Console when this happens?

Is anyone else's system sound being disabled by Spotifree?

**Comment by joshwertheim** [comment]
For me it's only been Spotify sound. Hasn't happened at all today. It's definitely sporadic. I'm trying to be observant. If it happens again I'll check out my Console and get back to you with some logs.

**Comment by Usbloom** [comment]
Version 1.6.1 doesn't always work for me (Maverick 10.9.5). An half the time, the sound isn't muted or sometimes Spotify (1.0.1.1060.gc75ebdfd)  suddenly crashed. … (?)
But thank you already for the job! and I'm sure that everything will be fine soon !

**Comment by fehmi** [comment]
I think i found! If ad plays after the last song in a playlist Spotify stuck at mute state.

Spotifree 1.6.1
Spotify 1.0.1.1060.gc75ebdfd

**Comment by ArtemGordinsky** [comment]
That is really helpful. Thanks, @fehmi!

**Comment by Usbloom** [comment]
I notice that spotifree works when with a specifically Spotify advertising (hits etc.) but not with an ads of a trademark.

**Comment by aravind-pg** [comment]
I'm not sure the commit above actually made it to the packaged form of the app, because the current version num is 1.6.1, whereas in the commit it looks like it's been updated to 1.6.2, and the issue still occurs occasionally. Please update the app on the spotifree.gordinskiy.com website if so. Thanks for your work on this app!

In the future, also consider tagging release points and using GitHub's releases feature so that we can download straight from here and also see what commits made it into a release.

**Comment by ArtemGordinsky** [comment]
Hey guys,
Finally got some time to work on an update. It should catch all ads now, and not get stuck at "muting" state. Can you try it out? http://d.pr/f/19FIk

**Comment by fehmi** [comment]
I tried and It is working perfect now. Not stuck at "muting" state anymore. Thank you very much.

**Comment by fehmi** [comment]
The problem still exist. I don't know when it happens but happens from time to time.

**Comment by ArtemGordinsky** [comment]
@fehmi I have taken another stab at fixing these and other issues. Any help with testing will be appreciated: http://d.pr/f/T6oq

**Comment by tonlam** [comment]
Hi guys I still have this issue.
