### ISSUE TITLE
Latest version 1.6.1 doesn't mute ads

### ISSUE THREAD

**Issue by pchhetri** [ArtemGordinsky/Spotifree#51]

**Comment by ArtemGordinsky** [comment]
1. What are the versions of your Spotify and Spotifree apps?
2. Would you please open your Console (Applications/Utilities/Console.app) and search for anything related to Spotifree?

**Comment by ianobermiller** [comment]
Also stopped working for me, and crashes on start. Here are matching logs from Console:

```
3/19/15 11:15:21.928 AM Spotifree[82257]: warning: failed to get scripting definition from /Applications/Spotify.app; it may not be scriptable.
3/19/15 11:15:21.929 AM Spotifree[82257]: -[SBApplication playerState]: unrecognized selector sent to instance 0x618000045dc0
3/19/15 11:15:21.930 AM Spotifree[82257]: An uncaught exception was raised
3/19/15 11:15:21.930 AM Spotifree[82257]: -[SBApplication playerState]: unrecognized selector sent to instance 0x618000045dc0
3/19/15 11:15:21.930 AM Spotifree[82257]: (
	0   CoreFoundation                      0x00007fff86d7466c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff905f476e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff86d776dd -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff86cbeaa4 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff86cbe618 _CF_forwarding_prep_0 + 120
	5   Spotifree                           0x0000000100002394 Spotifree + 9108
	6   Spotifree                           0x0000000100001ba7 Spotifree + 7079
	7   Spotifree                           0x0000000100001c1e Spotifree + 7198
	8   Spotifree                           0x0000000100003055 Spotifree + 12373
	9   CoreFoundation                      0x00007fff86c8285f -[NSSet makeObjectsPerformSelector:] + 223
	10  AppKit                              0x00007fff8e9195cd -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1216
	11  AppKit                              0x00007fff8e429605 loadNib + 384
	12  AppKit                              0x00007fff8e99a5ab +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
	13  AppKit                              0x00007fff8e428cd5 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	14  AppKit                              0x00007fff8e428aa1 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	15  AppKit                              0x00007fff8e424549 NSApplicationMain + 605
	16  Spotifree                           0x0000000100001824 Spotifree + 6180
	17  ???                                 0x0000000000000001 0x0 + 1
)
3/19/15 11:15:21.930 AM Spotifree[82257]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBApplication playerState]: unrecognized selector sent to instance 0x618000045dc0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff86d7466c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff905f476e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff86d776dd -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff86cbeaa4 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff86cbe618 _CF_forwarding_prep_0 + 120
	5   Spotifree                           0x0000000100002394 Spotifree + 9108
	6   Spotifree                           0x0000000100001ba7 Spotifree + 7079
	7   Spotifree                           0x0000000100001c1e Spotifree + 7198
	8   Spotifree                           0x0000000100003055 Spotifree + 12373
	9   CoreFoundation                      0x00007fff86c8285f -[NSSet makeObjectsPerformSelector:] + 223
	10  AppKit                              0x00007fff8e9195cd -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1216
	11  AppKit                              0x00007fff8e429605 loadNib + 384
	12  AppKit                              0x00007fff8e99a5ab +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
	13  AppKit                              0x00007fff8e428cd5 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	14  AppKit                              0x00007fff8e428aa1 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	15  AppKit                              0x00007fff8e424549 NSApplicationMain + 605
	16  Spotifree                           0x0000000100001824 Spotifree + 6180
	17  ???                                 0x0000000000000001 0x0 + 1
)
3/19/15 11:15:22.507 AM com.apple.xpc.launchd[1]: (de.eneas.Spotifree.80688[82257]) Service exited due to signal: Abort trap: 6
3/19/15 11:15:22.535 AM ReportCrash[82260]: Saved crash report for Spotifree[82257] version 1.5 (1.5) to /Users/iano/Library/Logs/DiagnosticReports/Spotifree_2015-03-19-111522_iano-mbp.crash

**Comment by ArtemGordinsky** [comment]
@ianobermiller Thanks for the log!
I see you're using Spotifree 1.5. Have you tried 1.6.1?

**Comment by ianobermiller** [comment]
@ArtemGordinsky I thought of that just as I was posting this. Updating both resolved the issue.

**Comment by pchhetri** [comment]
@ArtemGordinsky v. 1.6.1 no console logs unfortunately.

![](http://cl.ly/image/3v0M3u3y1718/Image%202015-03-19%20at%201.31.26%20PM.png)

**Comment by ArtemGordinsky** [comment]
Okay, thanks. I think Spotifree should work better with 1.x versions now. Have you tried updating?

**Comment by omikun** [comment]
Hi, I have v 1.6.1 and Spotify 1.0.2.6.g9977a14b running on OS X 10.10.2 and Spotifree does not recognize Spotify is playing.

I get a series of this from console:
3/19/15 2:37:17.287 PM Spotifree[451]: AppleEvents: Send port for process has no send right, port=( port:22443/0x57ab rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/19/15 2:40:47.988 PM Spotifree[451]: AppleEvents: Send port for process has no send right, port=( port:22443/0x57ab rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/19/15 2:49:50.372 PM Spotifree[10999]: -[SBApplication playerState]: unrecognized selector sent to instance 0x610000045b50
3/19/15 2:49:50.373 PM Spotifree[10999]: Cannot check if Spotify is playing: -[SBApplication playerState]: unrecognized selector sent to instance 0x610000045b50

I tried restarting both apps and the OS but I get the same errors.

**Comment by ArtemGordinsky** [comment]
@omikun If you restart Spotifree but leave Spotify open, do you get a prompt from Spotifree saying Spotify must be restarted?

**Comment by pchhetri** [comment]
@ArtemGordinsky  working now, thank you. 

![](http://1.bp.blogspot.com/-oGhT8P7_J-A/UShJmtI34MI/AAAAAAAABTY/Sv_dSrGMOMk/s400/lucille-bluth-celebration-gif.gif)

**Comment by omikun** [comment]
@ArtemGordinsky No I do not get that prompt. What should I do?

**Comment by ArtemGordinsky** [comment]
@pchhetri Great :)

@omikun It would be nice if you could upload your Spotify app somewhere and give me a link.

**Comment by omikun** [comment]
I redownloaded and install both the latest spotify and spotifree. I got the prompt to restart spotify but it still didn't detect it was playing, so I downloaded the recommended v1.1 of spotify and now it works!

**Comment by pbojinov** [comment]
It wasn't working for me either using v1.6.1 Spotifre, until I upgraded my pre-1.0 Spotify to 1.0.2.6.

**Comment by Usbloom** [comment]
I do not understand why, but spotifree works a while (an hour or two) and after, it doesn't mute any ads. It must be restarted and spotify too .(?)
spotifree : 1.6.1
spotify : 1.0.2.6.

**Comment by kalmufti** [comment]
I'm having the same issue, spotifree unable to detect spotify. 
Spotifree: Version 1.6.1
Spotify: 1.0.2.6.g9977a14b

**Comment by thetroublemaker** [comment]
Spotify: 0.9.10.14 (this version was the last to have subscribed list new song counts near the list)
Spotifree: 1.6.1
OS: MAC / Yosemie
Issue: Does not mute ads.

**Comment by thetroublemaker** [comment]
.

**Comment by doctordjbrown** [comment]
Hiya. I'm having a non-muting day. Have downloaded the latest of everything and I get this

![screen shot 2015-04-23 at 11 09 27](https://cloud.githubusercontent.com/assets/619051/7294936/81d81f58-e9a9-11e4-929c-930ef412a9d6.png)

Using Spotify 1.0.3.101
and Spotifree 1.6.1

Any help gratefully received.

![screen shot 2015-04-23 at 11 11 05](https://cloud.githubusercontent.com/assets/619051/7294943/900e8256-e9a9-11e4-9a60-674c3264392f.png)
![screen shot 2015-04-23 at 11 10 46](https://cloud.githubusercontent.com/assets/619051/7294944/9038ad2e-e9a9-11e4-9f34-9e841101e8be.png)

**Comment by ArtemGordinsky** [comment]
I will release a new update this weekend, which should resolve most of the issues. Meanwhile, I would much appreciate if you tried it out and reported any and all issues you encounter. The test build is here: http://d.pr/f/T6oq

**Comment by doctordjbrown** [comment]
Hi Artem

Seems to be working fine again.

Thank you for your efforts.

Regards

DJ
_________________________




Dr D J Hamblin-Brown
Human Capital Valuation Ltd
Greenhedges Hall, Mark Cross
East Sussex, TN6 3PA, UK
www.humancapitalvaluation.com
m: +44 (0) 7881 814 110
t/f: +44 (0) 7092 1234 89

**Comment by rsanchezsaez** [comment]
This issue can be closed.
