### ISSUE TITLE
Can't close Spotify if Spotifree open

### ISSUE THREAD

**Issue by fehmi** [ArtemGordinsky/Spotifree#54]
If I try to quit Spotify when Spotifree is open, Spotify can't quit. Pretend to quit for a sec and open instantly again. If I close Spotifree then everything is normal. 

Spotify (1.0.3.101.gbfa97dfe)
Spotifree (1.6.2)

**Comment by ArtemGordinsky** [comment]
Should be fixed in this update: http://d.pr/f/T6oq
Please check and tell me how it goes.

**Comment by fehmi** [comment]
I downloaded the file you linked and replace with mine. Seems OK, I can close Spotify now :)
My Spotifree version was 1.6.2 but the version of the new file is "1.6.2" also. What is the difference? Just curious.
