### ISSUE TITLE
New Spotify update breaks Spotifree

### ISSUE THREAD

**Issue by asherism** [ArtemGordinsky/Spotifree#55]
New Spotify update also includes videos now...

**Comment by ArtemGordinsky** [comment]
What version is this?

**Comment by asherism** [comment]
1.0.4.90.g0b6df40b

looks like it's time to downgrade :)

**Comment by ArtemGordinsky** [comment]
Thanks. Can you try [this version](http://d.pr/f/T6oq)? It should work with 1.0.4 (no changes for the video ads though).

**Comment by asherism** [comment]
Sorry.. downgraded to 0.9.15.. where, unfortunately, spotifree isn't working either.

**Comment by asherism** [comment]
Gonna try with the latest commit and report back.

**Comment by ArtemGordinsky** [comment]
Have you tried the build I posted in my previous comment? It contains the latest commit.

**Comment by rsanchezsaez** [comment]
Spotifree works for me on 1.0.4.90.g0b6df40b. Try reinstalling Spotifree after updating Spotify.

I don't have video ads, though.

**Comment by ArtemGordinsky** [comment]
Duplicates #58 as far as I can see.
