### ISSUE TITLE
Spotifree leaves Spotify muted if an ad comes after last track

### ISSUE THREAD

**Issue by rsanchezsaez** [ArtemGordinsky/Spotifree#56]
If an ad comes after the last track when listening a single album, Spotify stops after playing the ad, and remains muted.

The next time you go to play something, you have to manually move the volume slider up.

**Comment by ArtemGordinsky** [comment]
Have you tried 1.6.2? I have just released it.

**Comment by rsanchezsaez** [comment]
This was on 1.6.1: I'll try the new version and report back.

**Comment by ArtemGordinsky** [comment]
Any updates?

**Comment by rsanchezsaez** [comment]
Yeah, this seems to be fixed. Thanks!

**Comment by ArtemGordinsky** [comment]
You're welcome!
