### ISSUE TITLE
Spotifree is detecting local files as ads and muting them

### ISSUE THREAD

**Issue by lkjasdhui** [ArtemGordinsky/Spotifree#57]

**Comment by ArtemGordinsky** [comment]
1. Does this happen for all of your local music?
2. What are the versions of your Spotify and Spotifree apps?

It would also be helpful if you ran [this script](https://gist.github.com/ArtemGordinsky/8bc551502e6ca2d73809) and showed me the results, like this:
![screen shot 2015-05-17 at 9 11 28 am](https://cloud.githubusercontent.com/assets/1506254/7669302/21d79ee2-fc75-11e4-92db-d511243ec069.png)

**Comment by lkjasdhui** [comment]
It's only muting some of my local music (about half of it) and i can't spot any pattern in which songs it is muting. 
I'm using Spotifree 1.6.2 and Spotify 1.0.4.90.g0b6df40b.
![screen shot 2015-05-17 at 18 29 09](https://cloud.githubusercontent.com/assets/12223201/7671351/bb4ad3f2-fcc3-11e4-99a2-ae49ed12a0ca.png)

**Comment by ArtemGordinsky** [comment]
I've just released a new version that should fix this issue. You can update your app and tell me how it goes :)
