### ISSUE TITLE
video ads

### ISSUE THREAD

**Issue by lch48a** [ArtemGordinsky/Spotifree#58]
hello, thanks for the great work, which i've been using for a long time now. 
i know you said that video ads cannot be muted. 
the thing is, now that video ads have become pervasive (one every 10 minutes or so), and because they are particularly loud and nasty, spotifree becomes useless if we cannot mute them.
is it absolutely sure that there will never be a way to mute them? 
thanks!!

**Comment by ArtemGordinsky** [comment]
Sorry, but Spotify makes it pretty hard to detect and mute video ads, and I still haven't figured out a way to do it. Maybe I would, but I've been finding it increasingly difficult to carve out time to work on Spotifree.
