### ISSUE TITLE
Spotifree not working on 1.0.14.124.g4dfabc51

### ISSUE THREAD

**Issue by joshwertheim** [ArtemGordinsky/Spotifree#65]
I think that new update broke it.

**Comment by joshwertheim** [comment]
Only seems to happen sometimes. Maybe when there's a video ad (which can't be muted) followed by a regular audio ad? I'll look into it more.

**Comment by mjball** [comment]
Spotifree is definitely not muting video ads in 1.0.18.60.g5fe0413d.

**Comment by ArtemGordinsky** [comment]
Duplicates #52, if I'm not mistaken. Please read my response there.
