### ISSUE TITLE
Updates not working on OS X El Capitan

### ISSUE THREAD

**Issue by pedrokleiz** [ArtemGordinsky/Spotifree#67]
Hello,

I've being dealing with some minor issues with Spotifree.
Every time I try to update it shows this: 
<img width="421" alt="screen shot 2015-12-17 at 15 16 46" src="https://cloud.githubusercontent.com/assets/6828704/11880886/5e106394-a4d1-11e5-99a8-f019f3165ced.png">

Keep up with the good work.

Best Regards,
Pedro

EDIT: just saw that videos are impossible to mute.

**Comment by ArtemGordinsky** [comment]
Hi Pedro,

Please answer a couple of questions:
1. Do you still have this issue?
2. Does (http://spotifree.gordinskiy.com/appcast.xml)[this link] open in your browser?
3. What is the version of your Spotifree app?

**Comment by pedrokleiz** [comment]
1. Yes
2. 
<img width="1680" alt="screen shot 2015-12-21 at 01 41 30" src="https://cloud.githubusercontent.com/assets/6828704/11924890/000f00ba-a784-11e5-8bcf-a3240c003509.png">
3. 
<img width="286" alt="screen shot 2015-12-21 at 01 42 00" src="https://cloud.githubusercontent.com/assets/6828704/11924895/0dc4e936-a784-11e5-970e-9a32d9d21819.png">

**Comment by ArtemGordinsky** [comment]
Thanks.
A couple more questions:
1. Do you see anything mentioning Spotifree or Sparkle in the logs (Console)?
2. Are you 10.11?

**Comment by pedrokleiz** [comment]
1. Can you give the commands to try and update it CLI?
2. I'm on El Captain Open Beta, I'm currently on 10.11.3.

On Mon, Dec 21, 2015 at 2:59 PM, Artem Gordinsky <notifications@github.com>
wrote:

> Thanks.
> A couple more questions:
> 1. Do you see anything mentioning Spotifree or Sparkle in the logs
> (Console)?
> 2. Are you 10.11?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArtemGordinsky/Spotifree/issues/67#issuecomment-166403374>
> .
>



-- 
Best Regards,
Pedro Cleis
