### ISSUE TITLE
I'm seeing this message in Console constantly, maybe 15 times a second...

### ISSUE THREAD

**Issue by cy2k** [ArtemGordinsky/Spotifree#78]
3/31/16 12:18:03.765 PM Spotifree[1461]: AppleEvents: Send port for process has no send right, port=( port:30287/0x764f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread

I'm running latest Yosemite.

**Comment by ArtemGordinsky** [comment]
Hi,
This is a known bug in OS X. Fixed in El Capitan.
