### ISSUE TITLE
Newest Spotify seems to fool Spotifree

### ISSUE THREAD

**Issue by j-mckitrick** [ArtemGordinsky/Spotifree#81]
I've noticed SOME recent ads getting past Spotifree.  Here are 2 changes in behavior that might be related to the issue:

1. muting my sound during an ad used to pause Spotify, but it no longer does
2. during ads, the 'Spotify is playing' menu item in Spotifree says Spotify is *not* playing.

Perhaps they have changed the mechanism that Spotifree was using to recognize when Spotify is playing?

**Comment by ArtemGordinsky** [comment]
Hi,
Thanks for reporting!
Are those video ads, by any chance? If they are, then it's a known issue (#52).

**Comment by j-mckitrick** [comment]
Ah, yes I see. Maybe someone will figure it out.

On Mon, May 30, 2016 at 3:16 AM Artem Gordinsky <notifications@github.com>
wrote:

> Hi,
> Thanks for reporting!
> Are those video ads, by any chance? If they are, then it's a known issue (
> #52 <https://github.com/ArtemGordinsky/Spotifree/issues/52>).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ArtemGordinsky/Spotifree/issues/81#issuecomment-222427360>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAfnqWDgeFBjFBSkBclJBFFdRstY6liKks5qGo63gaJpZM4Invhg>
> .
>
-- 
Jonathon McKitrick

**Comment by ArtemGordinsky** [comment]
Duplicates #52
