### ISSUE TITLE
Spotify becomes unmuted for last ~1 second of advertisement

### ISSUE THREAD

**Issue by tomglynch** [ArtemGordinsky/Spotifree#87]
Spotify seems to become unmuted slightly early, leaving the last word or so of the ad unmuted before switching to the next song.

**Comment by Trosterud** [comment]
Yeah I get the same thing. Looks like this issue (which was fixed before this project was rewritten in Swift.
Eliminate tiny duration of ad sound #61
https://github.com/ArtemGordinsky/Spotifree/pull/61/commits/771a725e4fcc5b195894e7026e8a52f5f6c5619b

I guess a smiliar kind of solution would work here. Probably in Spotifree/Spotifree/SpotifyManager.swift around line 67 or 108.

Any idea on how to actually implement it?

**Comment by michaelsilver** [comment]
Any update on this?

**Comment by samkim1729** [comment]
Issue still exists.

**Comment by tomglynch** [comment]
Had a look but couldn't work out the cause.

**Comment by jaywilliams** [comment]
I downloaded the source code and added a simple one second delay to fix this.
You can see my pull request here: #96
